title: Creating an Android chat app
description: Create a Android application that enables users to message each other
products:
  - client-sdk

introduction:
  title: Introduction to this task
  description: This task shows you how to create a Android chat application using the Android Client SDK.
  content: |
    # Introduction
    In this task, you will learn how to create and configure a Client SDK Application and then code a web app that enables two users to send messages to each other.

    First, you will create a Conversation and two Users. Then, you will authenticate these Users and add them to the Conversation as Members.

    Finally, you will implement chat functionality in your application, including the ability to view and send messages and be notified when a new message appears in Conversation.

    The source code is available [on GitHub](https://github.com/nexmo-community/client-sdk-android-tutorial-messaging).

prerequisites:
  - create-nexmo-account
  - install-nodejs
  - install-nexmo-cli-beta
  - install-android-studio

tasks:
  - client-sdk/android-in-app-messaging-chat/create-application
  - client-sdk/android-in-app-messaging-chat/create-conversation
  - client-sdk/android-in-app-messaging-chat/create-users
  - client-sdk/android-in-app-messaging-chat/add-users-to-conversation
  - client-sdk/android-in-app-messaging-chat/generate-jwts
  - client-sdk/android-in-app-messaging-chat/starter-project
  - client-sdk/android-in-app-messaging-chat/initialize-client
  - client-sdk/android-in-app-messaging-chat/authenticate-users
  - client-sdk/android-in-app-messaging-chat/fetch-conversation
  - client-sdk/android-in-app-messaging-chat/fetch-events
  - client-sdk/android-in-app-messaging-chat/send-message
  - client-sdk/android-in-app-messaging-chat/receive-new-messages

conclusion:
  title: What's next?
  description: What else can you do with the Client SDK?
  content: |

    # What's next?

    For the complete version please see the Android Studio project in the `kotlin-completed` folder of the `git` repository you've cloned ([GitHub](https://github.com/nexmo-community/client-sdk-android-tutorial-messaging)).

    You can do a lot more with the Client SDK. See [Client SDK documentation](/client-sdk/overview).

    We want to hear what ideas you have in mind? Contact us at <a href="mailto:devrel@nexmo.com">devrel@nexmo.com</a>

    
