# Hanselminutes Landing Page Config

title: "Client SDK"
meta_title: "Client SDK Intro"

rows:
  - columns:
    - entries: 
      - type: header
        header:
          title: 
            text: "Welcome to the Nexmo Client SDK"
            align: center
          subtitle:
            text: "Prebuilt web, iOS and Android SDKs for all of your Messaging and Voice"
            align: center
            type: large
          icon: 
            name: "icon-rocket"
            color: "blue-dark"
      - type: action_button
        action_button:
          text: "Create a Nexmo account"
          url: "https://dashboard.nexmo.com/sign-up?utm_source=nexmo_developer"
          type: "primary"
          large: true
          center_button: true
  - columns:
    - entries:
        - type: line_divider

  - columns:
    - entries:
      - type: header
        header:
          title:
            text: "Messaging"
            align: center
          icon:
            name: "icon-chat"
            color: "blue-dark"
    - entries:
      - type: header
        header:
          title:
            text: "Voice"
            align: center
          icon:
            name: "icon-call"
            color: "blue-dark"
  - columns:
    - entries:
      - type: call_to_action
        call_to_action:
          title: "Build your own messaging platform"
          subtitle: "Though I'm not sure why you'd want to, we give you<br /> everything you need! Messages, typing indicators, the lot<br /><br />"
          icon:
            name: "icon-inbox"
            color: "red-dark"
          url: "javascript:alert('Not yet implemented');"
      - type: call_to_action
        call_to_action:
          title: "Build a chatbot"
          subtitle: "They're all the rage, didn't you hear?<br /><br />"
          icon:
            name: "icon-happy"
            color: "yellow-dark"
          url: "javascript:alert('Not yet implemented');"
      - type: call_to_action
        call_to_action:
          title: "Customer Support"
          subtitle: "Support your customers in realtime with IP messaging<br /><br />"
          icon:
            name: "icon-user"
            color: "green-dark"
          url: "javascript:alert('Not yet implemented');"
    - entries:
      - type: call_to_action
        call_to_action:
          title: "Phone to Phone"
          subtitle: "Make calls between two phones, anywhere in the world<br /><br />"
          icon:
            name: "icon-call-forward"
            color: "yellow-dark"
          url: "javascript:alert('Not yet implemented');"
      - type: call_to_action
        call_to_action:
          title: "Phone to IP"
          subtitle: "Nexmo In-App Voice uses WebRTC and includes all the essentials<br /> you need to build a feature-rich voice experience.<br /><br />"
          icon:
            name: "icon-mobile"
            color: "green-dark"
          url: "/task/pstn-to-ip-client-sdk"
      - type: call_to_action
        call_to_action:
          title: "IP to Phone"
          subtitle: "Nexmo In-App Video uses WebRTC and includes all the essentials you need<br /> to build a feature-rich video experience.<br /><br />"
          icon:
            name: "icon-app"
            color: "red-dark"
          url: "javascript:alert('Not yet implemented');"


  - columns:
    - entries:
        - type: line_divider
  - columns:
    - entries:
      - type: join_slack
      - type: text
        text:
          content: "<center>Connect with the Developer Relations team to ask questions and provide feedback about your experience with the Client SDK</center>"
  - columns:
    - entries:
        - type: line_divider


  - columns:
    - entries:
        - type: section_header
          section_header:
            title: Developer Guides
            icon:
              name: "icon-flash-2"
              color: "blue-dark"
  - columns:
    - entries:
      - type: card
        card:
          title: Configure push notifications
          text: |
              Push notifications are a key part of your application. Without them, your user won't know when
              their phone is ringing! We make it really easy to integrate push notifications in to your application.
          url: "javascript:alert('Not implemented');"
    - entries:
      - type: card
        card:
          title: Click to Call
          text: |
              Ever seen those click-to-call buttons on websites and wondered how they work? Follow our Click to Call
              guide and learn how you can build it yourself! Have your phone ring every time someone clicks a button 
              on your website
          url: "javascript:alert('Not implemented');"
    - entries:
      - type: card
        card:
          title: Inviting Users
          text: |
              Before a user can participate in a conversation, they need to be invited. You can invite them using
              the server-side library or using the Client SDK
          url: "javascript:alert('Not implemented');"
